import jsPDF from 'jspdf'

interface ScoreData {
  jobTitle: string
  overallScore: number
  atsScore: number
  sections: { experience: number; skills: number; education: number; formatting: number }
  matchedKeywords: string[]
  missingKeywords: string[]
  strengths: string[]
  improvements: string[]
  summary: string
}

export function exportScorePDF(score: ScoreData, resumeFilename: string) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(108, 99, 255)
  doc.rect(0, 0, pageWidth, 35, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('HireGuru — Score Report', 14, 22)

  // Meta
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, pageWidth - 14, 22, { align: 'right' })

  // Score circle area
  doc.setTextColor(30, 30, 50)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(`Role: ${score.jobTitle || 'Not specified'}`, 14, 48)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 120)
  doc.text(`Resume: ${resumeFilename}`, 14, 56)

  // Overall score
  doc.setFillColor(245, 245, 255)
  doc.roundedRect(14, 62, 80, 40, 3, 3, 'F')
  doc.setTextColor(108, 99, 255)
  doc.setFontSize(32)
  doc.setFont('helvetica', 'bold')
  doc.text(`${score.overallScore}`, 54, 86, { align: 'center' })
  doc.setFontSize(10)
  doc.text('Overall Score', 54, 96, { align: 'center' })

  doc.setFillColor(245, 245, 255)
  doc.roundedRect(100, 62, 96, 40, 3, 3, 'F')
  doc.setTextColor(30, 30, 50)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Section Breakdown', 148, 72, { align: 'center' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 100)
  const sections = [
    ['ATS', score.atsScore],
    ['Experience', score.sections.experience],
    ['Skills', score.sections.skills],
    ['Formatting', score.sections.formatting],
  ]
  sections.forEach(([label, val], i) => {
    doc.text(`${label}: ${val}%`, 104, 82 + i * 6)
  })

  // Summary
  let y = 115
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 50)
  doc.text('Summary', 14, y)
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 100)
  const summaryLines = doc.splitTextToSize(score.summary, pageWidth - 28)
  doc.text(summaryLines, 14, y)
  y += summaryLines.length * 6 + 8

  // Matched keywords
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 50)
  doc.text('✓ Matched Keywords', 14, y)
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(62, 175, 130)
  doc.text(score.matchedKeywords.join('  •  '), 14, y)
  y += 12

  // Missing keywords
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 50)
  doc.text('✗ Missing Keywords', 14, y)
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(200, 80, 80)
  doc.text(score.missingKeywords.join('  •  '), 14, y)
  y += 12

  // Strengths
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 50)
  doc.text('Strengths', 14, y)
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 100)
  score.strengths.forEach(s => {
    doc.text(`→  ${s}`, 14, y)
    y += 7
  })
  y += 4

  // Improvements
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 50)
  doc.text('Improvements', 14, y)
  y += 7
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 100)
  score.improvements.forEach(s => {
    doc.text(`→  ${s}`, 14, y)
    y += 7
  })

  // Footer
  doc.setFontSize(9)
  doc.setTextColor(180, 180, 200)
  doc.text('Generated by HireGuru — Built by Dharun Kabil', pageWidth / 2, 285, { align: 'center' })

  doc.save(`HireGuru_Score_${score.jobTitle || 'Report'}_${Date.now()}.pdf`)
}